using System;
using System.Collections.Generic;

namespace WhisperSubs.Providers
{
    /// <summary>
    /// Whisper's full language names mapped to the codes it uses, copied from whisper.cpp's
    /// <c>g_lang</c> table (src/whisper.cpp, v1.8.4). whisper-server and OpenAI-style endpoints answer
    /// with the full name (<c>whisper_lang_str_full</c>), and every caller compares codes, so a name
    /// missing here would reach a caller as a language that matches nothing.
    /// </summary>
    internal static class WhisperLanguages
    {
        internal static readonly IReadOnlyDictionary<string, string> CodeByName =
            new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["english"] = "en",
                ["chinese"] = "zh",
                ["german"] = "de",
                ["spanish"] = "es",
                ["russian"] = "ru",
                ["korean"] = "ko",
                ["french"] = "fr",
                ["japanese"] = "ja",
                ["portuguese"] = "pt",
                ["turkish"] = "tr",
                ["polish"] = "pl",
                ["catalan"] = "ca",
                ["dutch"] = "nl",
                ["arabic"] = "ar",
                ["swedish"] = "sv",
                ["italian"] = "it",
                ["indonesian"] = "id",
                ["hindi"] = "hi",
                ["finnish"] = "fi",
                ["vietnamese"] = "vi",
                ["hebrew"] = "he",
                ["ukrainian"] = "uk",
                ["greek"] = "el",
                ["malay"] = "ms",
                ["czech"] = "cs",
                ["romanian"] = "ro",
                ["danish"] = "da",
                ["hungarian"] = "hu",
                ["tamil"] = "ta",
                ["norwegian"] = "no",
                ["thai"] = "th",
                ["urdu"] = "ur",
                ["croatian"] = "hr",
                ["bulgarian"] = "bg",
                ["lithuanian"] = "lt",
                ["latin"] = "la",
                ["maori"] = "mi",
                ["malayalam"] = "ml",
                ["welsh"] = "cy",
                ["slovak"] = "sk",
                ["telugu"] = "te",
                ["persian"] = "fa",
                ["latvian"] = "lv",
                ["bengali"] = "bn",
                ["serbian"] = "sr",
                ["azerbaijani"] = "az",
                ["slovenian"] = "sl",
                ["kannada"] = "kn",
                ["estonian"] = "et",
                ["macedonian"] = "mk",
                ["breton"] = "br",
                ["basque"] = "eu",
                ["icelandic"] = "is",
                ["armenian"] = "hy",
                ["nepali"] = "ne",
                ["mongolian"] = "mn",
                ["bosnian"] = "bs",
                ["kazakh"] = "kk",
                ["albanian"] = "sq",
                ["swahili"] = "sw",
                ["galician"] = "gl",
                ["marathi"] = "mr",
                ["punjabi"] = "pa",
                ["sinhala"] = "si",
                ["khmer"] = "km",
                ["shona"] = "sn",
                ["yoruba"] = "yo",
                ["somali"] = "so",
                ["afrikaans"] = "af",
                ["occitan"] = "oc",
                ["georgian"] = "ka",
                ["belarusian"] = "be",
                ["tajik"] = "tg",
                ["sindhi"] = "sd",
                ["gujarati"] = "gu",
                ["amharic"] = "am",
                ["yiddish"] = "yi",
                ["lao"] = "lo",
                ["uzbek"] = "uz",
                ["faroese"] = "fo",
                ["haitian creole"] = "ht",
                ["pashto"] = "ps",
                ["turkmen"] = "tk",
                ["nynorsk"] = "nn",
                ["maltese"] = "mt",
                ["sanskrit"] = "sa",
                ["luxembourgish"] = "lb",
                ["myanmar"] = "my",
                ["tibetan"] = "bo",
                ["tagalog"] = "tl",
                ["malagasy"] = "mg",
                ["assamese"] = "as",
                ["tatar"] = "tt",
                ["hawaiian"] = "haw",
                ["lingala"] = "ln",
                ["hausa"] = "ha",
                ["bashkir"] = "ba",
                ["javanese"] = "jw",
                ["sundanese"] = "su",
                ["cantonese"] = "yue",
            };

        /// <summary>The code for a full language name, or null when whisper has no such language.</summary>
        internal static string? CodeFor(string name)
            => CodeByName.TryGetValue(name.Trim(), out var code) ? code : null;
    }
}
